import { COMPLETABLE_STATUS } from '@prisma/client';

export const STATUS_LABEL = {
	[COMPLETABLE_STATUS.COMPLETED]: 'Completed',
	[COMPLETABLE_STATUS.IN_PROGRESS]: 'In progress',
	[COMPLETABLE_STATUS.TO_DO]: 'To do',
	[COMPLETABLE_STATUS.ARCHIVED]: 'Archived',
} as const;

export const AVAILABLE_TRANSITIONS = {
	[COMPLETABLE_STATUS.ARCHIVED]: [],
	[COMPLETABLE_STATUS.COMPLETED]: [],
	[COMPLETABLE_STATUS.IN_PROGRESS]: [
		COMPLETABLE_STATUS.COMPLETED,
		COMPLETABLE_STATUS.TO_DO,
		COMPLETABLE_STATUS.ARCHIVED,
	],
	[COMPLETABLE_STATUS.TO_DO]: [
		COMPLETABLE_STATUS.IN_PROGRESS,
		COMPLETABLE_STATUS.COMPLETED,
		COMPLETABLE_STATUS.ARCHIVED,
	],
} as const;

export const STATUS_ICON = {
	[COMPLETABLE_STATUS.COMPLETED]: 'i-lucide-check-circle',
	[COMPLETABLE_STATUS.ARCHIVED]: 'i-lucide-archive',
	[COMPLETABLE_STATUS.TO_DO]: 'i-lucide-bed',
	[COMPLETABLE_STATUS.IN_PROGRESS]: 'i-lucide-arrow-left-right',
} as const;
