-- CreateEnum
CREATE TYPE "COMPLETABLE_STATUS" AS ENUM ('TO_DO', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGHH');

-- AlterTable
ALTER TABLE "Goal" ADD COLUMN     "priority" "Priority" NOT NULL,
ADD COLUMN     "status" "COMPLETABLE_STATUS" NOT NULL;

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "priority" "Priority" NOT NULL,
DROP COLUMN "status",
ADD COLUMN     "status" "COMPLETABLE_STATUS" NOT NULL DEFAULT 'TO_DO';

-- DropEnum
DROP TYPE "TASK_STATUS";
